on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  ci_ubuntu:
    runs-on: ubuntu-22.04 # currently ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.2, 3.1, 3.0, 2.7, 2.6, 2.5]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install xmllint
        run: sudo apt-get install -y libpng-dev libjpeg-dev
      - run: bundle install
      - run: bundle exec rake compile
      - run: bundle exec rake

  ci_mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.2, 3.1, 3.0, 2.7]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - run: bundle exec rake compile
      - run: bundle exec rake